[[profile]]
name = "ilmbase"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "exec  niri msg action focus-monitor \"Dell Inc. DELL P2317H HH77Y7B4AM6L\"", "exec ~/.config/mango/scripts/set_layout.sh"]
    [[profile.output]]
    enable = true
    search = ["m=DELL P2317H", "s=HH77Y7B4AM6L", "v=Dell Inc."]
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.0
    adaptive_sync = false
    transform = "normal"

    [[profile.output]]
    enable = true
    search = ["m=DELL P2317H", "s=HH77Y75BAEDB", "v=Dell Inc."]
    mode = "1920x1080@60Hz"
    position = "1920,0"
    scale = 1.0
    adaptive_sync = false
    transform = "90"
