[[profile]]
name = "ast-work"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"","exec ~/.config/shikane/move_workspaces_work.py", "exec ./p14s-audio-sink.sh"]
    [[profile.output]]
    enable = true
    search = ["m=0xD291", "s=", "v=AU Optronics"]
    mode = "1920x1200@60.026Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"

    [[profile.output]]
    enable = true
    search = ["m=DELL U2415", "s=7MT0196C30JU", "v=Dell Inc."]
    mode = "1920x1200@59.95Hz"
    position = "3840,0"
    scale = 1.0
    # transform = "270"
    transform = "90"

    [[profile.output]]
    enable = true
    search = ["m=DELL U2415", "s=7MT018B3062L", "v=Dell Inc."]
    mode = "1920x1200@59.95Hz"
    position = "1920,0"
    scale = 1.0
    transform = "normal"

[[profile]]
name = "ilmbase"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\""]
    [[profile.output]]
    enable = true
    search = ["m=DELL P2317H", "s=HH77Y7B4AM6L", "v=Dell Inc."]
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.0
    adaptive_sync = false
    transform = "normal"

    [[profile.output]]
    enable = true
    search = ["m=DELL P2317H", "s=HH77Y75BAEDB", "v=Dell Inc."]
    mode = "1920x1080@60Hz"
    position = "1920,0"
    scale = 1.0
    adaptive_sync = false
    transform = "90"

    [[profile.output]]
    enable = true
    search = ["m=0xD291", "s=", "v=AU Optronics"]
    mode = "1920x1200@60.026Hz"
    position = "3000,0"
    scale = 1.0
    transform = "normal"

[[profile]]
name = "ammera"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"","exec ~/.config/shikane/move_workspaces_ammera_office.py"]
    [[profile.output]]
    enable = true
    search = ["m=0xD291", "s=", "v=AU Optronics"]
    mode = "1920x1200@60.026Hz"
    position = "1920,0"
    scale = 1.0
    transform = "normal"

    [[profile.output]]
    enable = true
    search = ["m=BenQ GW2780", "s=ETFAL03748SL0"]
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

[[profile]]
name = "denkraum"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"","exec wl-present mirror eDP-1"]
    [[profile.output]]
    enable = true
    search = ["m=0xD291", "s=", "v=AU Optronics"]
    mode = "1920x1200@60.026Hz"
    position = "1920,0"
    scale = 1.0
    transform = "normal"

    [[profile.output]]
    enable = true
    search = ["m=SyncMaster"]
    mode = "1920x1080@60.00Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

[[profile]]
name = "undock"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "exec killall wl-mirror"]
    [[profile.output]]
    enable = true
    search = ["m=0xD291", "s=", "v=AU Optronics"]
    mode = "1920x1200@60.026Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
