[[profile]]
name = "ilmbase"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"","exec killall -SIGUSR2 waybar","hyprctl dispatch workspace -- 1"]
    [[profile.output]]
    enable = true
    search = ["n/eDP-1"]
    mode = "1920x1080@60.026Hz"
    position = "1920,0"
    scale = 1.0
    transform = "normal"

    [[profile.output]]
    enable = true
    search = ["m=DELL P2317H", "s=HH77Y7B4AM6L", "v=Dell Inc."]
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

[[profile]]
name = "ammera"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"","exec ~/.config/shikane/move_workspaces_ammera.py","exec killall -SIGUSR2 waybar","hyprctl dispatch workspace -- 1"]
    [[profile.output]]
    enable = true
    search = ["n/eDP-1"]
    mode = "1920x1080@60.026Hz"
    position = "1920,0"
    scale = 1.0
    transform = "normal"

    [[profile.output]]
    enable = true
    search = ["m=BenQ GW2780", "s=ETFAL03748SL0"]
    mode = "1920x1080@60Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false


[[profile]]
name = "undock"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"","exec killall -SIGUSR2 waybar"]
    [[profile.output]]
    enable = true
    search = ["n/eDP-1"]
    mode = "1920x1080@60.026Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
